#!/usr/bin/env python3
"""
generate_form.py
Generates frmPleadingsChecker.frm programmatically.

All controls are created at runtime in UserForm_Initialize so no
.frx binary file is needed.  The form is sized generously to avoid
a squished layout on standard displays.

Usage:
    python3 generate_form.py            # writes Combined/frmPleadingsChecker.frm
    python3 generate_form.py OUT.frm    # writes to a custom path
"""

import sys
import os

# ── Form dimensions (twips: 1 pt = 20 twips, 1 inch = 1440 twips) ──
FORM_WIDTH  = 10800   # ~540 px / 7.5 in
FORM_HEIGHT = 16200   # ~810 px / 11.25 in

# ── Section layout constants (points — used in VBA code) ──
# These appear in the generated VBA, not in the FRM header.
# The FRM header uses twips; VBA controls use points.

def generate_frm(output_path: str) -> None:
    """Generate the complete frmPleadingsChecker.frm file."""

    # ── FRM header (twips) ──────────────────────────────────
    header = f"""\
VERSION 5.00
Begin {{C62A69F0-16DC-11CE-9E98-00AA00574A4F}} frmPleadingsChecker
   Caption         =   "Pleadings Checker"
   ClientHeight    =   {FORM_HEIGHT}
   ClientLeft      =   120
   ClientTop       =   465
   ClientWidth     =   {FORM_WIDTH}
   StartUpPosition =   1  'CenterOwner
End"""

    # ── VB Attributes ───────────────────────────────────────
    attributes = """\
Attribute VB_Name = "frmPleadingsChecker"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = True
Attribute VB_Exposed = False"""

    # ── VBA code ────────────────────────────────────────────
    vba_code = r"""' ============================================================
' frmPleadingsChecker.frm
' UserForm for the Pleadings Checker rule engine.
'
' ALL controls are created dynamically in UserForm_Initialize
' so that no .frx binary file is needed.  The form adapts its
' rule checkbox list from the engine metadata automatically.
'
' Generated by generate_form.py — do not hand-edit the
' control-creation section.
' ============================================================
Option Explicit

' ── Module-level variables ────────────────────────────────────
Private ruleConfig      As Object  ' Scripting.Dictionary
Private ruleDisplayMap  As Object  ' Scripting.Dictionary (rule_name -> label)
Private ruleKeys()      As String  ' Ordered array of rule names
Private ruleCheckboxes  As Collection  ' MSForms.CheckBox controls

' Controls created at runtime (module-level so event subs can reference them)
Private WithEvents btnRun           As MSForms.CommandButton
Private WithEvents btnHighlight     As MSForms.CommandButton
Private WithEvents btnExport        As MSForms.CommandButton
Private WithEvents btnClose         As MSForms.CommandButton
Private WithEvents btnSelectAll     As MSForms.CommandButton
Private WithEvents btnDeselectAll   As MSForms.CommandButton
Private WithEvents btnAddBrand      As MSForms.CommandButton
Private WithEvents btnRemoveBrand   As MSForms.CommandButton
Private WithEvents btnSaveBrands    As MSForms.CommandButton
Private WithEvents btnLoadBrands    As MSForms.CommandButton

Private fraRules        As MSForms.Frame
Private txtStartPage    As MSForms.TextBox
Private txtEndPage      As MSForms.TextBox
Private lstBrands       As MSForms.ListBox
Private txtBrandCorrect As MSForms.TextBox
Private txtBrandIncorrect As MSForms.TextBox
Private chkAddComments  As MSForms.CheckBox
Private chkTrackedChanges As MSForms.CheckBox
Private lblStatus       As MSForms.Label

Private lastResults     As Collection

' ════════════════════════════════════════════════════════════
'  FORM INITIALISATION — creates all controls at runtime
' ════════════════════════════════════════════════════════════
Private Sub UserForm_Initialize()
    Dim lbl As MSForms.Label
    Dim yPos As Single

    ' ── Overall form padding ──────────────────────────────────
    Const PAD As Single = 12
    Const FULL_W As Single = 516     ' usable width (form ~540 - 2*PAD)
    Const BTN_W As Single = 108
    Const BTN_H As Single = 28
    Const TXT_H As Single = 24
    Const CHK_H As Single = 20
    Const LBL_H As Single = 16
    Const SEC_GAP As Single = 14     ' gap between sections
    Const ITEM_GAP As Single = 4     ' gap within sections

    yPos = PAD

    ' ══════════════════════════════════════════════════════════
    '  SECTION 1: Rule Selection
    ' ══════════════════════════════════════════════════════════
    Set lbl = Me.Controls.Add("Forms.Label.1", "lblRulesHeader")
    With lbl
        .Caption = "Rules"
        .Left = PAD: .Top = yPos: .Width = 200: .Height = LBL_H
        .Font.Size = 10: .Font.Bold = True
    End With
    yPos = yPos + LBL_H + ITEM_GAP

    ' Scrollable rules frame (tall enough for ~18 visible rows)
    Set fraRules = Me.Controls.Add("Forms.Frame.1", "fraRules")
    With fraRules
        .Caption = ""
        .Left = PAD: .Top = yPos
        .Width = FULL_W - BTN_W - SEC_GAP
        .Height = 360
        .ScrollBars = fmScrollBarsVertical
        .KeepScrollBarsVisible = fmScrollBarsVertical
    End With

    ' Select All / Deselect All buttons (right of frame)
    Dim btnX As Single
    btnX = PAD + fraRules.Width + ITEM_GAP

    Set btnSelectAll = Me.Controls.Add("Forms.CommandButton.1", "btnSelectAll")
    With btnSelectAll
        .Caption = "Select All"
        .Left = btnX: .Top = yPos: .Width = BTN_W: .Height = BTN_H
    End With

    Set btnDeselectAll = Me.Controls.Add("Forms.CommandButton.1", "btnDeselectAll")
    With btnDeselectAll
        .Caption = "Deselect All"
        .Left = btnX: .Top = yPos + BTN_H + ITEM_GAP
        .Width = BTN_W: .Height = BTN_H
    End With

    yPos = yPos + fraRules.Height + SEC_GAP

    ' ── Build dynamic rule checkboxes ─────────────────────────
    Set ruleConfig = PleadingsEngine.InitRuleConfig()
    Set ruleDisplayMap = PleadingsEngine.GetRuleDisplayNames()

    Dim keys As Variant
    keys = ruleConfig.keys
    Dim nRules As Long
    nRules = ruleConfig.Count
    ReDim ruleKeys(0 To nRules - 1)
    Dim k As Long
    For k = 0 To nRules - 1
        ruleKeys(k) = CStr(keys(k))
    Next k

    BuildRuleCheckboxList nRules

    ' ══════════════════════════════════════════════════════════
    '  SECTION 2: Page Range
    ' ══════════════════════════════════════════════════════════
    Set lbl = Me.Controls.Add("Forms.Label.1", "lblPageHeader")
    With lbl
        .Caption = "Page Range (optional)"
        .Left = PAD: .Top = yPos: .Width = 200: .Height = LBL_H
        .Font.Size = 10: .Font.Bold = True
    End With
    yPos = yPos + LBL_H + ITEM_GAP

    Set lbl = Me.Controls.Add("Forms.Label.1", "lblStartPage")
    With lbl
        .Caption = "Start Page:"
        .Left = PAD: .Top = yPos + 4: .Width = 72: .Height = LBL_H
    End With

    Set txtStartPage = Me.Controls.Add("Forms.TextBox.1", "txtStartPage")
    With txtStartPage
        .Left = PAD + 78: .Top = yPos: .Width = 60: .Height = TXT_H
        .Text = ""
    End With

    Set lbl = Me.Controls.Add("Forms.Label.1", "lblEndPage")
    With lbl
        .Caption = "End Page:"
        .Left = PAD + 156: .Top = yPos + 4: .Width = 66: .Height = LBL_H
    End With

    Set txtEndPage = Me.Controls.Add("Forms.TextBox.1", "txtEndPage")
    With txtEndPage
        .Left = PAD + 228: .Top = yPos: .Width = 60: .Height = TXT_H
        .Text = ""
    End With

    yPos = yPos + TXT_H + SEC_GAP

    ' ══════════════════════════════════════════════════════════
    '  SECTION 3: Brand Rules
    ' ══════════════════════════════════════════════════════════
    Set lbl = Me.Controls.Add("Forms.Label.1", "lblBrandHeader")
    With lbl
        .Caption = "Brand Rules"
        .Left = PAD: .Top = yPos: .Width = 200: .Height = LBL_H
        .Font.Size = 10: .Font.Bold = True
    End With
    yPos = yPos + LBL_H + ITEM_GAP

    Set lstBrands = Me.Controls.Add("Forms.ListBox.1", "lstBrands")
    With lstBrands
        .Left = PAD: .Top = yPos: .Width = FULL_W - BTN_W - SEC_GAP
        .Height = 108
    End With

    ' Brand action buttons (right of list)
    btnX = PAD + lstBrands.Width + ITEM_GAP
    Dim brandBtnY As Single
    brandBtnY = yPos

    Set btnAddBrand = Me.Controls.Add("Forms.CommandButton.1", "btnAddBrand")
    With btnAddBrand
        .Caption = "Add"
        .Left = btnX: .Top = brandBtnY: .Width = BTN_W: .Height = BTN_H
    End With
    brandBtnY = brandBtnY + BTN_H + ITEM_GAP

    Set btnRemoveBrand = Me.Controls.Add("Forms.CommandButton.1", "btnRemoveBrand")
    With btnRemoveBrand
        .Caption = "Remove"
        .Left = btnX: .Top = brandBtnY: .Width = BTN_W: .Height = BTN_H
    End With
    brandBtnY = brandBtnY + BTN_H + ITEM_GAP

    Set btnSaveBrands = Me.Controls.Add("Forms.CommandButton.1", "btnSaveBrands")
    With btnSaveBrands
        .Caption = "Save Rules"
        .Left = btnX: .Top = brandBtnY: .Width = BTN_W: .Height = BTN_H
    End With
    brandBtnY = brandBtnY + BTN_H + ITEM_GAP

    Set btnLoadBrands = Me.Controls.Add("Forms.CommandButton.1", "btnLoadBrands")
    With btnLoadBrands
        .Caption = "Load Rules"
        .Left = btnX: .Top = brandBtnY: .Width = BTN_W: .Height = BTN_H
    End With

    yPos = yPos + lstBrands.Height + ITEM_GAP

    ' Brand input fields
    Set lbl = Me.Controls.Add("Forms.Label.1", "lblCorrectForm")
    With lbl
        .Caption = "Correct Form:"
        .Left = PAD: .Top = yPos + 4: .Width = 84: .Height = LBL_H
    End With

    Set txtBrandCorrect = Me.Controls.Add("Forms.TextBox.1", "txtBrandCorrect")
    With txtBrandCorrect
        .Left = PAD + 90: .Top = yPos: .Width = 150: .Height = TXT_H
    End With

    Set lbl = Me.Controls.Add("Forms.Label.1", "lblIncorrectVars")
    With lbl
        .Caption = "Incorrect Variants:"
        .Left = PAD + 252: .Top = yPos + 4: .Width = 108: .Height = LBL_H
    End With

    Set txtBrandIncorrect = Me.Controls.Add("Forms.TextBox.1", "txtBrandIncorrect")
    With txtBrandIncorrect
        .Left = PAD + 366: .Top = yPos: .Width = 150: .Height = TXT_H
    End With

    yPos = yPos + TXT_H + SEC_GAP

    ' ══════════════════════════════════════════════════════════
    '  SECTION 4: Options
    ' ══════════════════════════════════════════════════════════
    Set lbl = Me.Controls.Add("Forms.Label.1", "lblOptionsHeader")
    With lbl
        .Caption = "Options"
        .Left = PAD: .Top = yPos: .Width = 200: .Height = LBL_H
        .Font.Size = 10: .Font.Bold = True
    End With
    yPos = yPos + LBL_H + ITEM_GAP

    Set chkAddComments = Me.Controls.Add("Forms.CheckBox.1", "chkAddComments")
    With chkAddComments
        .Caption = "Add comments to document"
        .Left = PAD: .Top = yPos: .Width = 240: .Height = CHK_H
        .Value = True
    End With
    yPos = yPos + CHK_H + ITEM_GAP

    Set chkTrackedChanges = Me.Controls.Add("Forms.CheckBox.1", "chkTrackedChanges")
    With chkTrackedChanges
        .Caption = "Apply suggestions as tracked changes"
        .Left = PAD: .Top = yPos: .Width = 280: .Height = CHK_H
        .Value = True
    End With
    yPos = yPos + CHK_H + SEC_GAP

    ' ══════════════════════════════════════════════════════════
    '  SECTION 5: Action Buttons
    ' ══════════════════════════════════════════════════════════
    Const ACT_BTN_H As Single = 36
    Const ACT_BTN_W As Single = 114
    Const ACT_GAP As Single = 12

    Set btnRun = Me.Controls.Add("Forms.CommandButton.1", "btnRun")
    With btnRun
        .Caption = "Run Checks"
        .Left = PAD: .Top = yPos: .Width = ACT_BTN_W: .Height = ACT_BTN_H
        .Font.Bold = True
    End With

    Set btnHighlight = Me.Controls.Add("Forms.CommandButton.1", "btnHighlight")
    With btnHighlight
        .Caption = "Apply Suggestions"
        .Left = PAD + ACT_BTN_W + ACT_GAP: .Top = yPos
        .Width = ACT_BTN_W + 12: .Height = ACT_BTN_H
    End With

    Set btnExport = Me.Controls.Add("Forms.CommandButton.1", "btnExport")
    With btnExport
        .Caption = "Export Report"
        .Left = PAD + 2 * (ACT_BTN_W + ACT_GAP) + 12: .Top = yPos
        .Width = ACT_BTN_W: .Height = ACT_BTN_H
    End With

    Set btnClose = Me.Controls.Add("Forms.CommandButton.1", "btnClose")
    With btnClose
        .Caption = "Close"
        .Left = PAD + 3 * (ACT_BTN_W + ACT_GAP) + 12: .Top = yPos
        .Width = 84: .Height = ACT_BTN_H
    End With

    yPos = yPos + ACT_BTN_H + SEC_GAP

    ' ══════════════════════════════════════════════════════════
    '  SECTION 6: Status Bar
    ' ══════════════════════════════════════════════════════════
    Set lblStatus = Me.Controls.Add("Forms.Label.1", "lblStatus")
    With lblStatus
        .Caption = "Ready. Select rules and click Run."
        .Left = PAD: .Top = yPos: .Width = FULL_W: .Height = LBL_H
        .Font.Size = 9
    End With

    ' ── Load brand list ───────────────────────────────────────
    RefreshBrandList
End Sub

' ════════════════════════════════════════════════════════════
'  BUILD DYNAMIC RULE CHECKBOX LIST
' ════════════════════════════════════════════════════════════
Private Sub BuildRuleCheckboxList(nRules As Long)
    Set ruleCheckboxes = New Collection

    Dim topPos As Single
    Dim chk As MSForms.CheckBox
    Dim displayLabel As String
    Dim i As Long

    topPos = 6  ' initial top padding inside frame

    For i = 0 To nRules - 1
        If ruleDisplayMap.Exists(ruleKeys(i)) Then
            displayLabel = CStr(i + 1) & ". " & CStr(ruleDisplayMap(ruleKeys(i)))
        Else
            displayLabel = CStr(i + 1) & ". " & ruleKeys(i)
        End If

        Set chk = fraRules.Controls.Add("Forms.CheckBox.1", "chkRule_" & i)
        With chk
            .Caption = displayLabel
            .Left = 6
            .Top = topPos
            .Width = fraRules.InsideWidth - 18
            .Height = 18
            .Value = True
            .Font.Size = 9
        End With

        ruleCheckboxes.Add chk
        topPos = topPos + 20
    Next i

    fraRules.ScrollHeight = topPos + 6
End Sub

' ════════════════════════════════════════════════════════════
'  RUN BUTTON
' ════════════════════════════════════════════════════════════
Private Sub btnRun_Click()
    If ActiveDocument Is Nothing Then
        MsgBox "Please open a document first.", vbExclamation, "Pleadings Checker"
        Exit Sub
    End If

    ' Sync rule config from dynamic checkboxes
    Dim i As Long
    For i = 1 To ruleCheckboxes.Count
        Dim rName As String
        rName = ruleKeys(i - 1)
        If ruleConfig.Exists(rName) Then
            ruleConfig(rName) = CBool(ruleCheckboxes(i).Value)
        End If
    Next i

    ' Set page range if specified
    Dim startPg As Long, endPg As Long
    startPg = 0: endPg = 0
    If IsNumeric(txtStartPage.Text) And Len(txtStartPage.Text) > 0 Then
        startPg = CLng(txtStartPage.Text)
    End If
    If IsNumeric(txtEndPage.Text) And Len(txtEndPage.Text) > 0 Then
        endPg = CLng(txtEndPage.Text)
    End If
    PleadingsEngine.SetPageRange startPg, endPg

    ' Run checks
    lblStatus.Caption = "Running checks..."
    Me.Repaint
    DoEvents

    Set lastResults = PleadingsEngine.RunAllPleadingsRules(ActiveDocument, ruleConfig)

    ' Show summary
    Dim summary As String
    summary = PleadingsEngine.GetIssueSummary(lastResults)

    If lastResults.Count = 0 Then
        lblStatus.Caption = "No issues found."
        MsgBox "No issues found " & Chr(8212) & " document looks clean.", vbInformation, "Pleadings Checker"
    Else
        lblStatus.Caption = lastResults.Count & " issue(s) found."
        MsgBox summary, vbInformation, "Pleadings Checker " & Chr(8212) & " Results"
    End If
End Sub

' ════════════════════════════════════════════════════════════
'  HIGHLIGHT / APPLY SUGGESTIONS BUTTON
' ════════════════════════════════════════════════════════════
Private Sub btnHighlight_Click()
    If lastResults Is Nothing Then
        MsgBox "Run checks first before highlighting.", vbExclamation, "Pleadings Checker"
        Exit Sub
    End If
    If lastResults.Count = 0 Then
        MsgBox "No issues to highlight.", vbInformation, "Pleadings Checker"
        Exit Sub
    End If

    Dim addComments As Boolean
    addComments = (chkAddComments.Value = True)

    lblStatus.Caption = "Applying suggestions..."
    Me.Repaint
    DoEvents

    If chkTrackedChanges.Value = True Then
        PleadingsEngine.ApplySuggestionsAsTrackedChanges ActiveDocument, lastResults, addComments
    Else
        PleadingsEngine.ApplyHighlights ActiveDocument, lastResults, addComments
    End If

    lblStatus.Caption = lastResults.Count & " issue(s) processed."
    MsgBox lastResults.Count & " issue(s) processed in document." & vbCrLf & _
           IIf(chkTrackedChanges.Value, "Auto-fix suggestions applied as tracked changes.", _
               "Issues highlighted.") & vbCrLf & _
           IIf(addComments, "Comments added for non-auto-fix items.", ""), _
           vbInformation, "Pleadings Checker"
End Sub

' ════════════════════════════════════════════════════════════
'  EXPORT REPORT BUTTON
' ════════════════════════════════════════════════════════════
Private Sub btnExport_Click()
    If lastResults Is Nothing Then
        MsgBox "Run checks first before exporting.", vbExclamation, "Pleadings Checker"
        Exit Sub
    End If

    Dim reportPath As String
    If ActiveDocument.Path <> "" Then
        reportPath = ActiveDocument.Path & "\" & _
                     Replace(ActiveDocument.Name, ".docx", "") & _
                     "_pleadings_report.json"
    Else
        reportPath = Environ("TEMP") & "\pleadings_report.json"
    End If

    lblStatus.Caption = "Exporting report..."
    Me.Repaint
    DoEvents

    Dim summary As String
    summary = PleadingsEngine.GenerateReport(lastResults, reportPath)

    lblStatus.Caption = "Report saved."
    MsgBox "Report saved to:" & vbCrLf & reportPath & vbCrLf & vbCrLf & summary, _
           vbInformation, "Pleadings Checker " & Chr(8212) & " Report"
End Sub

' ════════════════════════════════════════════════════════════
'  SELECT ALL / DESELECT ALL
' ════════════════════════════════════════════════════════════
Private Sub btnSelectAll_Click()
    Dim i As Long
    For i = 1 To ruleCheckboxes.Count
        ruleCheckboxes(i).Value = True
    Next i
End Sub

Private Sub btnDeselectAll_Click()
    Dim i As Long
    For i = 1 To ruleCheckboxes.Count
        ruleCheckboxes(i).Value = False
    Next i
End Sub

' ════════════════════════════════════════════════════════════
'  BRAND RULES MANAGEMENT
' ════════════════════════════════════════════════════════════
Private Sub RefreshBrandList()
    lstBrands.Clear
    On Error Resume Next
    Dim brands As Object
    Set brands = Application.Run("Rules_Brands.GetBrandRules")
    If Err.Number <> 0 Then
        Err.Clear
        On Error GoTo 0
        Exit Sub
    End If
    On Error GoTo 0
    If brands Is Nothing Then Exit Sub
    Dim key As Variant
    For Each key In brands.keys
        lstBrands.AddItem CStr(key) & " -> " & CStr(brands(key))
    Next key
End Sub

Private Sub btnAddBrand_Click()
    Dim correctForm As String
    Dim incorrectVariants As String
    correctForm = Trim(txtBrandCorrect.Text)
    incorrectVariants = Trim(txtBrandIncorrect.Text)

    If correctForm = "" Or incorrectVariants = "" Then
        MsgBox "Enter both the correct form and incorrect variants.", _
               vbExclamation, "Brand Rules"
        Exit Sub
    End If

    On Error Resume Next
    Application.Run "Rules_Brands.AddBrandRule", correctForm, incorrectVariants
    If Err.Number <> 0 Then
        MsgBox "Brand rules module not loaded.", vbExclamation, "Brand Rules"
        Err.Clear
    End If
    On Error GoTo 0

    txtBrandCorrect.Text = ""
    txtBrandIncorrect.Text = ""
    RefreshBrandList
End Sub

Private Sub btnRemoveBrand_Click()
    If lstBrands.ListIndex < 0 Then
        MsgBox "Select a brand rule to remove.", vbExclamation, "Brand Rules"
        Exit Sub
    End If

    Dim entry As String
    entry = lstBrands.List(lstBrands.ListIndex)
    Dim correctForm As String
    correctForm = Left(entry, InStr(entry, " -> ") - 1)

    On Error Resume Next
    Application.Run "Rules_Brands.RemoveBrandRule", correctForm
    If Err.Number <> 0 Then Err.Clear
    On Error GoTo 0

    RefreshBrandList
End Sub

Private Sub btnSaveBrands_Click()
    Dim brandFile As String
    brandFile = Environ("APPDATA") & "\PleadingsChecker\brand_rules.txt"

    On Error Resume Next
    MkDir Environ("APPDATA") & "\PleadingsChecker"
    On Error GoTo 0

    On Error Resume Next
    Application.Run "Rules_Brands.SaveBrandRules", brandFile
    If Err.Number <> 0 Then
        MsgBox "Brand rules module not loaded.", vbExclamation, "Brand Rules"
        Err.Clear
        On Error GoTo 0
        Exit Sub
    End If
    On Error GoTo 0

    MsgBox "Brand rules saved to:" & vbCrLf & brandFile, vbInformation, "Brand Rules"
End Sub

Private Sub btnLoadBrands_Click()
    Dim brandFile As String
    brandFile = Environ("APPDATA") & "\PleadingsChecker\brand_rules.txt"

    If Dir(brandFile) = "" Then
        MsgBox "No saved brand rules found at:" & vbCrLf & brandFile, _
               vbExclamation, "Brand Rules"
        Exit Sub
    End If

    On Error Resume Next
    Application.Run "Rules_Brands.LoadBrandRules", brandFile
    If Err.Number <> 0 Then
        MsgBox "Brand rules module not loaded.", vbExclamation, "Brand Rules"
        Err.Clear
        On Error GoTo 0
        Exit Sub
    End If
    On Error GoTo 0

    RefreshBrandList
    MsgBox "Brand rules loaded.", vbInformation, "Brand Rules"
End Sub

' ════════════════════════════════════════════════════════════
'  CLOSE BUTTON
' ════════════════════════════════════════════════════════════
Private Sub btnClose_Click()
    Unload Me
End Sub"""

    # ── Assemble the file ───────────────────────────────────
    content = header + "\n" + attributes + "\n" + vba_code + "\n"

    # Write with CRLF line endings for Office compatibility
    content_crlf = content.replace("\r\n", "\n").replace("\n", "\r\n")

    with open(output_path, "w", encoding="utf-8", newline="") as f:
        f.write(content_crlf)

    print(f"Generated: {output_path}")
    print(f"  Form size: {FORM_WIDTH}x{FORM_HEIGHT} twips "
          f"({FORM_WIDTH / 20:.0f}x{FORM_HEIGHT / 20:.0f} pt, "
          f"~{FORM_WIDTH / 20 * 96 / 72:.0f}x{FORM_HEIGHT / 20 * 96 / 72:.0f} px)")
    print(f"  No .frx dependency — all controls created at runtime")


if __name__ == "__main__":
    if len(sys.argv) > 1:
        out = sys.argv[1]
    else:
        out = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                           "frmPleadingsChecker.frm")
    generate_frm(out)
